### ISSUE TITLE
Missing validation that the password has been changed to the same one

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-security#45]
platform version = '0.0.1-SNAPSHOT'
jmix v 0.3.SNAPSHOT2408-202

TC: run app>create new user with password 1
user browser> change password > set 1 value>Ok
ER: validation that the passwod  has been changed to the same one
AR: changed successfully

**Comment by owlet1997** [comment]
TC:
1. Create new project -> run app
2. Open 'User browser'
3. Choose user -> change password -> set nothing in both fields
4. Save

AR:
![image](https://user-images.githubusercontent.com/45730069/109757072-82baef80-7c02-11eb-89a2-427ec269d936.png)

ER:
validation about empty password instead of unexpected error
