### ISSUE TITLE
Specific permissions registry

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-security#99]
To use in REST and UI.
Now REST doesn't return custom specific permissions at all.

**Comment by gorbunkov** [comment]
1. `SpecificPolicyInfoRegistry` has been created. The registry returns a list of specific policies available in the application. In order to be "registered" the specific policy must have a SpecificOperationAccessContenxt, e.g. 

```java
public class UiLoginToUiContext extends SpecificOperationAccessContext {

    public static final String NAME = "ui.loginToUi";

    public UiLoginToUiContext() {
        super(NAME);
    }
}
```

2. The Specific policy editor in the Resource role editor now allows selecting a specific policy from the dropdown list. The combo-box supports user input, the user may grant a specific permission even it is not in the list.

3. The `/rest/permissions` REST API endpoint now returns information about granted specific policies
